version: '2'
services:
  database:
    build: database
    container_name: centrio_database
    hostname: centrio_database
    restart: on-failure
    ports:
      - "27017:27017"
  payment-api:
    build: payment-api
    container_name: centrio_payment_api
    hostname: centrio_payment_api
    restart: on-failure
    links:
      - database
    depends_on:
      - database
    environment:
      - PORT=1337
      - MONGO_HOST=centrio_database
      - MONGO_PORT=27017
      - MONGO_DB=admin
      - CLIENT_ID=00a2cecf-57a9-495d-b337-05379481cea2
      - CLIENT_ID_SECRET=90f866f0-0bb1-419f-bfcc-abd3ce65d0e1
      - OAUTH_CREDENTIAL=MDBhMmNlY2YtNTdhOS00OTVkLWIzMzctMDUzNzk0ODFjZWEyOjkwZjg2NmYwLTBiYjEtNDE5Zi1iZmNjLWFiZDNjZTY1ZDBlMQ==
      - API_KEY=1b6e44be-df70-4013-8a75-3d7abd2a8046
      - API_SECRET=60766ed9-2480-4f47-ab3f-68a5a719b54d
    ports:
      - "1337:1337"
    networks:
      - centrio_default
      - bridge